apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-container
  template:
    metadata:
      labels:
        app: order-container
    spec:
      containers:
      - name: order
        image: linybin/order_server:1
        ports:
        - containerPort: 22222