apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-deployment
  labels:
    app: pricing-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pricingApp
  template:
    metadata:
      labels:
        app: pricingApp
    spec:
      containers:
      - name: pricing-app
        image: linybin/pricing
        ports:
        - containerPort: 8080